### ISSUE TITLE
Proper divisors vs prime factors

### ISSUE THREAD

**Issue by skaunov** [nodef/extra-bigint#7]
As an improvement please consider prime factors function, described at <https://www.geeksforgeeks.org/prime-factors-big-number/>. It has significantly smaller complexity than _proper divisors_ implemented currently, and returns basically same information in more convenient format. Actually if this function finds it way to the package, proper divisors could be constructed from it's output with the benefit from its performance.

(it also could be easily improved by stopping the search when _n == 1_)

**Comment by wolfram77** [comment]
I can have `primeFactors()` return `[factor_i, ...]`, and `primeFactorEntries()` return `[[factor_i, power_i]]`. I am assuming small arrays are optimized (for `primeFactorEntries()`). Any ideas why this might be a good/bad choice?

There could be several optimizations (such as skipping multiples of 3), but for the time being it makes sense to have a working implementation and tests. How do you find proper divisors from the rime factors? I guess it would be based on combinations.

Thanks @skaunov for your sharing.

**Comment by skaunov** [comment]
On Mon, Oct 31, 2022, 8:53 AM Subhajit Sahu ***@***.***>
wrote:

> I can have primeFactors() return [factor_i, ...], and primeFactorEntries()
> return [[factor_i, power_i]]. I am assuming small arrays are optimized
> (for primeFactorEntries()). Any ideas why this might be a good/bad choice?
>

Personally I chose a `Map` for me, with `key` as prime factor and `value` as `count` (see the code from the page I shared initially). Though I have no idea how well this choice would fit design of the package. I would say I just try to avoid folding arrays.

> There could be several optimizations (such as skipping multiples of 3),
> but for the time being it makes sense to have a working implementation and
> tests. How do you find proper divisors from the rime factors? I guess it
> would be based on combinations.
>
Correct me if I am wrong: all proper divisors are a multiplications of a
prime factor and integer _n_, where _n_ takes value from 1 to `count`. So
proper divisors can just multiply output of prime factors functions.

**Comment by wolfram77** [comment]
@skaunov Please see `primeFactors()` and `primeExponentials()`.
- `primeFactors()` returns an array of prime factors (only).
- `primeExponentials()` return an array of pairs of prime factors and their exponents.

I use an array of pairs as it can be easily converted to a `Map`, and allows binary search.

Also added `minPrimeFactor()` and `maxPrimeFactor()`.

**Comment by skaunov** [comment]
Looks like an improvement to me! Thank you. =)
